<settingsIndividualScreen>: 
    MDLabel: 
        id: title
        halign: "center"
        theme_font_size: "Custom"
        font_size: "30sp"
        style: "bold"
        size_hint_y: None
        height: dp(100)
        pos_hint: {"center_y": 0.8}
    MDIconButton: 
        id: button_back
        icon: "arrow-left-bold"
        style: "tonal"
        pos_hint: {"center_y": 0.7, "center_x": 0.5}
