<homeScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 20

        MDIcon:
            icon:"assets/icons/work-in-progress.png"
            pos_hint: {"center_x": 0.5, "center_y": 0.1}
            font_size : 300

        MDLabel:
            text: "Home Screen of Currency Converter"
            halign: 'center'
            font_size: 44

        MDRaisedButton:
            text: "Click Me"
            pos_hint: {"center_x": 0.5}
