<CheckItem>
    adaptive_height: True
    orientation: "horizontal"

    MDLabel:
        text: root.text
        adaptive_height: True
        size_hint_y: None
        padding_x: "12dp"
        pos_hint: {"x": 0}


    MDCheckbox:
        group: root.group
        size: dp(48), dp(48)
        adaptive_height: True
        size_hint: None, None
        on_release: root.parent.parent.show_ripple()
        on_press: root.parent.parent.show_ripple(False)