<comboBox>:
    size_hint_y:None
    height:dp(60)
    padding:dp(10)
    spacing:dp(10)

    MDLabel:
        id: label_option_name
        font_size: 26

    MDRectangleFlatIconButton:
        id: button_select
        on_release: root.open_drop_item_menu(self)
        pos_hint: {"center_x": .5, "center_y": .5}
        text: "Dark"
        font_size: 19
        icon: "arrow-down-drop-circle"
